services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./entrypoint.sh:/docker-entrypoint.sh
    environment:
      - PORT=${PORT}
    depends_on:
      - app_blue
      - app_green
    entrypoint: /docker-entrypoint.sh nginx -g 'daemon off;'

  app_blue:
    image: ${BLUE_IMAGE}
    ports:
      - "8081:${PORT}"
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue

  app_green:
    image: ${GREEN_IMAGE}
    ports:
      - "8082:${PORT}"
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green